erkankosluk/falcons-erp-ui-deploy@main:
  - source: public/
    dest: public/
  - source: src/
    dest: src/
  - source: .env.list
    dest: .env.list
  - source: .prettierrc.json
    dest: .prettierrc.json
  - source: Dockerfile
    dest: Dockerfile
  - source: bun.lockb
    dest: bun.lockb
  - source: index.html
    dest: index.html
  - source: package.json
    dest: package.json
  - source: tsconfig.json
    dest: tsconfig.json
  - source: tsconfig.node.json
    dest: tsconfig.node.json
  - source: vite.config.ts
    dest: vite.config.ts
  - source: README.md
    dest: README.md
  - source: launch_dev.sh
    dest: launch_dev.sh
  - source: conf/
    dest: conf/



