/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type {
  AdditionalCosts,
  AssignmentCards,
  AssignmentTransactions,
  BankAccounts,
  BankBranches,
  Banks,
  Branches,
  CashAccountTransactions,
  CashAccounts,
  Companies,
  CurrentAccountBankAccounts,
  CurrentAccountTransactions,
  CurrentAccounts,
  Departments,
  Depots,
  EmployeeOvertimes,
  EmployeePayments,
  Employees,
  ExpenseCards,
  ExpenseInvoices,
  FilteringRequest,
  FixtureCards,
  FixtureGroups,
  Invoices,
  Machines,
  MaterialCards,
  MaterialGroups,
  PaymentMethods,
  ProductCards,
  ProductGroups,
  Projects,
  Proposals,
  PublicHolidays,
  PurchaseOrders,
  Roles,
  Sections,
  ServiceCards,
  ServiceGroups,
  Shelves,
  TimeKeepings,
  TimeOffStatuses,
  TimeOffs,
  Units,
  Users
} from './model'
import { customMutator } from './customMutator';



/**
 * List Users. Supports filtering via rsql.
 */
export const users = (
    filteringRequest: FilteringRequest,
 signal?: AbortSignal
) => {
      
      
      return customMutator<Users>(
      {url: `/api/user/users`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: filteringRequest, signal
    },
      );
    }
  


/**
 * List Units. Supports filtering via rsql.
 */
export const units = (
    filteringRequest: FilteringRequest,
 signal?: AbortSignal
) => {
      
      
      return customMutator<Units>(
      {url: `/api/storage/units`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: filteringRequest, signal
    },
      );
    }
  


/**
 * List Shelves. Supports filtering via rsql.
 */
export const shelves = (
    filteringRequest: FilteringRequest,
 signal?: AbortSignal
) => {
      
      
      return customMutator<Shelves>(
      {url: `/api/storage/shelves`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: filteringRequest, signal
    },
      );
    }
  


/**
 * List ServiceGroups. Supports filtering via rsql.
 */
export const serviceGroups = (
    filteringRequest: FilteringRequest,
 signal?: AbortSignal
) => {
      
      
      return customMutator<ServiceGroups>(
      {url: `/api/storage/serviceGroups`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: filteringRequest, signal
    },
      );
    }
  


/**
 * List ServiceCards. Supports filtering via rsql.
 */
export const serviceCards = (
    filteringRequest: FilteringRequest,
 signal?: AbortSignal
) => {
      
      
      return customMutator<ServiceCards>(
      {url: `/api/storage/serviceCards`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: filteringRequest, signal
    },
      );
    }
  


/**
 * List ProductGroups. Supports filtering via rsql.
 */
export const productGroups = (
    filteringRequest: FilteringRequest,
 signal?: AbortSignal
) => {
      
      
      return customMutator<ProductGroups>(
      {url: `/api/storage/productGroups`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: filteringRequest, signal
    },
      );
    }
  


/**
 * List ProductCards. Supports filtering via rsql.
 */
export const productCards = (
    filteringRequest: FilteringRequest,
 signal?: AbortSignal
) => {
      
      
      return customMutator<ProductCards>(
      {url: `/api/storage/productCards`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: filteringRequest, signal
    },
      );
    }
  


/**
 * List MaterialGroups. Supports filtering via rsql.
 */
export const materialGroups = (
    filteringRequest: FilteringRequest,
 signal?: AbortSignal
) => {
      
      
      return customMutator<MaterialGroups>(
      {url: `/api/storage/materialGroups`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: filteringRequest, signal
    },
      );
    }
  


/**
 * List MaterialCards. Supports filtering via rsql.
 */
export const materialCards = (
    filteringRequest: FilteringRequest,
 signal?: AbortSignal
) => {
      
      
      return customMutator<MaterialCards>(
      {url: `/api/storage/materialCards`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: filteringRequest, signal
    },
      );
    }
  


/**
 * List Fixture Groups. Supports filtering via rsql.
 */
export const fixtureGroups = (
    filteringRequest: FilteringRequest,
 signal?: AbortSignal
) => {
      
      
      return customMutator<FixtureGroups>(
      {url: `/api/storage/fixtureGroups`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: filteringRequest, signal
    },
      );
    }
  


/**
 * List FixtureCards. Supports filtering via rsql.
 */
export const fixtureCards = (
    filteringRequest: FilteringRequest,
 signal?: AbortSignal
) => {
      
      
      return customMutator<FixtureCards>(
      {url: `/api/storage/fixtureCards`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: filteringRequest, signal
    },
      );
    }
  


/**
 * List AssignmentTransactions. Supports filtering via rsql.
 */
export const assignmentTransactions = (
    filteringRequest: FilteringRequest,
 signal?: AbortSignal
) => {
      
      
      return customMutator<AssignmentTransactions>(
      {url: `/api/storage/assignmentTransactions`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: filteringRequest, signal
    },
      );
    }
  


/**
 * List AssignmentCards. Supports filtering via rsql.
 */
export const assignmentCards = (
    filteringRequest: FilteringRequest,
 signal?: AbortSignal
) => {
      
      
      return customMutator<AssignmentCards>(
      {url: `/api/storage/assignmentCards`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: filteringRequest, signal
    },
      );
    }
  


/**
 * List Proposals. Supports filtering via rsql.
 */
export const proposals = (
    filteringRequest: FilteringRequest,
 signal?: AbortSignal
) => {
      
      
      return customMutator<Proposals>(
      {url: `/api/sales/proposals`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: filteringRequest, signal
    },
      );
    }
  


/**
 * List PurchaseOrders. Supports filtering via rsql.
 */
export const purchaseOrders = (
    filteringRequest: FilteringRequest,
 signal?: AbortSignal
) => {
      
      
      return customMutator<PurchaseOrders>(
      {url: `/api/purchasing/purchaseOrders`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: filteringRequest, signal
    },
      );
    }
  


/**
 * List Invoices. Supports filtering via rsql.
 */
export const getInvoices = (
    filteringRequest: FilteringRequest,
 signal?: AbortSignal
) => {
      
      
      return customMutator<Invoices>(
      {url: `/api/purchasing/invoices`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: filteringRequest, signal
    },
      );
    }
  


/**
 * List Current Accounts. Supports filtering via rsql.
 */
export const currentAccounts = (
    filteringRequest: FilteringRequest,
 signal?: AbortSignal
) => {
      
      
      return customMutator<CurrentAccounts>(
      {url: `/api/purchasing/currentAccounts`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: filteringRequest, signal
    },
      );
    }
  


/**
 * List Current Account Transactions. Supports filtering via rsql.
 */
export const getCurrentAccountTransactions = (
    filteringRequest: FilteringRequest,
 signal?: AbortSignal
) => {
      
      
      return customMutator<CurrentAccountTransactions>(
      {url: `/api/purchasing/currentAccountTransactions`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: filteringRequest, signal
    },
      );
    }
  


/**
 * List CurrentAccountBankAccounts. Supports filtering via rsql.
 */
export const currentAccountBankAccounts = (
    filteringRequest: FilteringRequest,
 signal?: AbortSignal
) => {
      
      
      return customMutator<CurrentAccountBankAccounts>(
      {url: `/api/purchasing/currentAccountBankAccounts`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: filteringRequest, signal
    },
      );
    }
  


/**
 * List AdditionalCosts. Supports filtering via rsql.
 */
export const additionalCosts = (
    filteringRequest: FilteringRequest,
 signal?: AbortSignal
) => {
      
      
      return customMutator<AdditionalCosts>(
      {url: `/api/purchasing/additionalCosts`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: filteringRequest, signal
    },
      );
    }
  


/**
 * List Projects. Supports filtering via rsql.
 */
export const projects = (
    filteringRequest: FilteringRequest,
 signal?: AbortSignal
) => {
      
      
      return customMutator<Projects>(
      {url: `/api/production/projects`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: filteringRequest, signal
    },
      );
    }
  


/**
 * List TimeKeepings. Supports filtering via rsql.
 */
export const timeKeepings = (
    filteringRequest: FilteringRequest,
 signal?: AbortSignal
) => {
      
      
      return customMutator<TimeKeepings>(
      {url: `/api/hr/timekeepings`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: filteringRequest, signal
    },
      );
    }
  


/**
 * List Employees. Supports filtering via rsql.
 */
export const employees = (
    filteringRequest: FilteringRequest,
 signal?: AbortSignal
) => {
      
      
      return customMutator<Employees>(
      {url: `/api/hr/employees`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: filteringRequest, signal
    },
      );
    }
  


/**
 * List Employee TimeOff Statuses. Supports filtering via rsql.
 */
export const employeeTimeOffStatuses = (
    filteringRequest: FilteringRequest,
 signal?: AbortSignal
) => {
      
      
      return customMutator<TimeOffStatuses>(
      {url: `/api/hr/employees/timeoffstatuses`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: filteringRequest, signal
    },
      );
    }
  


/**
 * List Employee timeoffs. Supports filtering via rsql.
 */
export const timeoffs = (
    id: number,
    filteringRequest: FilteringRequest,
 signal?: AbortSignal
) => {
      
      
      return customMutator<TimeOffs>(
      {url: `/api/hr/employee/${id}/timeoffs`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: filteringRequest, signal
    },
      );
    }
  


/**
 * List Employee - Employee Payments. Supports filtering via rsql.
 */
export const employeePayments = (
    id: number,
    filteringRequest: FilteringRequest,
 signal?: AbortSignal
) => {
      
      
      return customMutator<EmployeePayments>(
      {url: `/api/hr/employee/${id}/payments`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: filteringRequest, signal
    },
      );
    }
  


/**
 * List Employee - Employee Overtimes. Supports filtering via rsql.
 */
export const employeeOvertimes = (
    id: number,
    filteringRequest: FilteringRequest,
 signal?: AbortSignal
) => {
      
      
      return customMutator<EmployeeOvertimes>(
      {url: `/api/hr/employee/${id}/overtimes`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: filteringRequest, signal
    },
      );
    }
  


/**
 * List Banks. Supports filtering via rsql.
 */
export const banks = (
    filteringRequest: FilteringRequest,
 signal?: AbortSignal
) => {
      
      
      return customMutator<Banks>(
      {url: `/api/finance/banks`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: filteringRequest, signal
    },
      );
    }
  


/**
 * List Bank Branches. Supports filtering via rsql.
 */
export const bankBranches = (
    filteringRequest: FilteringRequest,
 signal?: AbortSignal
) => {
      
      
      return customMutator<BankBranches>(
      {url: `/api/finance/bankBranches`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: filteringRequest, signal
    },
      );
    }
  


/**
 * List Bank Accounts. Supports filtering via rsql.
 */
export const bankAccounts = (
    filteringRequest: FilteringRequest,
 signal?: AbortSignal
) => {
      
      
      return customMutator<BankAccounts>(
      {url: `/api/finance/bankAccounts`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: filteringRequest, signal
    },
      );
    }
  


/**
 * List Departments. Supports filtering via rsql.
 */
export const departments = (
    filteringRequest: FilteringRequest,
 signal?: AbortSignal
) => {
      
      
      return customMutator<Departments>(
      {url: `/api/company/departments`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: filteringRequest, signal
    },
      );
    }
  


/**
 * List Branches. Supports filtering via rsql.
 */
export const branches = (
    filteringRequest: FilteringRequest,
 signal?: AbortSignal
) => {
      
      
      return customMutator<Branches>(
      {url: `/api/company/branches`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: filteringRequest, signal
    },
      );
    }
  


/**
 * List Sections. Supports filtering via rsql.
 */
export const sections = (
    filteringRequest: FilteringRequest,
 signal?: AbortSignal
) => {
      
      
      return customMutator<Sections>(
      {url: `/api/admin/sections`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: filteringRequest, signal
    },
      );
    }
  


/**
 * List Roles. Supports filtering via rsql.
 */
export const roles = (
    filteringRequest: FilteringRequest,
 signal?: AbortSignal
) => {
      
      
      return customMutator<Roles>(
      {url: `/api/admin/roles`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: filteringRequest, signal
    },
      );
    }
  


/**
 * List Public Holidays. Supports filtering via rsql.
 */
export const publicHolidays = (
    filteringRequest: FilteringRequest,
 signal?: AbortSignal
) => {
      
      
      return customMutator<PublicHolidays>(
      {url: `/api/admin/publicHolidays`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: filteringRequest, signal
    },
      );
    }
  


/**
 * List PaymentMethods. Supports filtering via rsql.
 */
export const paymentMethods = (
    filteringRequest: FilteringRequest,
 signal?: AbortSignal
) => {
      
      
      return customMutator<PaymentMethods>(
      {url: `/api/admin/paymentMethods`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: filteringRequest, signal
    },
      );
    }
  


/**
 * List Machines. Supports filtering via rsql.
 */
export const machines = (
    filteringRequest: FilteringRequest,
 signal?: AbortSignal
) => {
      
      
      return customMutator<Machines>(
      {url: `/api/admin/machines`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: filteringRequest, signal
    },
      );
    }
  


/**
 * List Depots. Supports filtering via rsql.
 */
export const depots = (
    filteringRequest: FilteringRequest,
 signal?: AbortSignal
) => {
      
      
      return customMutator<Depots>(
      {url: `/api/admin/depots`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: filteringRequest, signal
    },
      );
    }
  


/**
 * List Companies. Supports filtering via rsql.
 */
export const companies = (
    filteringRequest: FilteringRequest,
 signal?: AbortSignal
) => {
      
      
      return customMutator<Companies>(
      {url: `/api/admin/companies`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: filteringRequest, signal
    },
      );
    }
  


/**
 * List ExpenseInvoices. Supports filtering via rsql.
 */
export const expenseInvoices = (
    filteringRequest: FilteringRequest,
 signal?: AbortSignal
) => {
      
      
      return customMutator<ExpenseInvoices>(
      {url: `/api/accounting/expenseInvoices`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: filteringRequest, signal
    },
      );
    }
  


/**
 * List ExpenseCards. Supports filtering via rsql.
 */
export const expenseCards = (
    filteringRequest: FilteringRequest,
 signal?: AbortSignal
) => {
      
      
      return customMutator<ExpenseCards>(
      {url: `/api/accounting/expenseCards`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: filteringRequest, signal
    },
      );
    }
  


/**
 * List CashAccounts. Supports filtering via rsql.
 */
export const cashAccounts = (
    filteringRequest: FilteringRequest,
 signal?: AbortSignal
) => {
      
      
      return customMutator<CashAccounts>(
      {url: `/api/accounting/cashAccounts`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: filteringRequest, signal
    },
      );
    }
  


/**
 * List CashAccountTransactions. Supports filtering via rsql.
 */
export const cashAccountTransactions = (
    filteringRequest: FilteringRequest,
 signal?: AbortSignal
) => {
      
      
      return customMutator<CashAccountTransactions>(
      {url: `/api/accounting/cashAccountTransactions`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: filteringRequest, signal
    },
      );
    }
  


