/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios';

import type {
  CashAccounts,
  FilteringRequest
} from './model';





/**
 * List CashAccounts. Supports filtering via rsql.
 */
export const cashAccounts = (
    filteringRequest: FilteringRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<CashAccounts>> => {
    
    
    return axios.default.post(
      `/api/accounting/cashAccounts`,
      filteringRequest,options
    );
  }



