/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import * as axios from 'axios';
import type {
  AxiosRequestConfig,
  AxiosResponse
} from 'axios'
import type {
  AdditionalCosts,
  AssignmentCards,
  AssignmentTransactions,
  BankAccounts,
  BankBranches,
  Banks,
  Branches,
  CashAccountTransactions,
  CashAccounts,
  Companies,
  CurrentAccountBankAccounts,
  CurrentAccountTransactions,
  CurrentAccounts,
  Departments,
  Depots,
  EmployeeOvertimes,
  EmployeePayments,
  Employees,
  ExpenseCards,
  ExpenseInvoices,
  FilteringRequest,
  FixtureCards,
  FixtureGroups,
  Invoices,
  Machines,
  MaterialCards,
  MaterialGroups,
  PaymentMethods,
  ProductCards,
  ProductGroups,
  Projects,
  Proposals,
  PublicHolidays,
  PurchaseOrders,
  Roles,
  Sections,
  ServiceCards,
  ServiceGroups,
  Shelves,
  TimeKeepings,
  TimeOffStatuses,
  TimeOffs,
  Units,
  Users
} from './model'



/**
 * List Users. Supports filtering via rsql.
 */
export const users = (
    filteringRequest: FilteringRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Users>> => {
    
    
    return axios.default.post(
      `/api/user/users`,
      filteringRequest,options
    );
  }



/**
 * List Units. Supports filtering via rsql.
 */
export const units = (
    filteringRequest: FilteringRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Units>> => {
    
    
    return axios.default.post(
      `/api/storage/units`,
      filteringRequest,options
    );
  }



/**
 * List Shelves. Supports filtering via rsql.
 */
export const shelves = (
    filteringRequest: FilteringRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Shelves>> => {
    
    
    return axios.default.post(
      `/api/storage/shelves`,
      filteringRequest,options
    );
  }



/**
 * List ServiceGroups. Supports filtering via rsql.
 */
export const serviceGroups = (
    filteringRequest: FilteringRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ServiceGroups>> => {
    
    
    return axios.default.post(
      `/api/storage/serviceGroups`,
      filteringRequest,options
    );
  }



/**
 * List ServiceCards. Supports filtering via rsql.
 */
export const serviceCards = (
    filteringRequest: FilteringRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ServiceCards>> => {
    
    
    return axios.default.post(
      `/api/storage/serviceCards`,
      filteringRequest,options
    );
  }



/**
 * List ProductGroups. Supports filtering via rsql.
 */
export const productGroups = (
    filteringRequest: FilteringRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ProductGroups>> => {
    
    
    return axios.default.post(
      `/api/storage/productGroups`,
      filteringRequest,options
    );
  }



/**
 * List ProductCards. Supports filtering via rsql.
 */
export const productCards = (
    filteringRequest: FilteringRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ProductCards>> => {
    
    
    return axios.default.post(
      `/api/storage/productCards`,
      filteringRequest,options
    );
  }



/**
 * List MaterialGroups. Supports filtering via rsql.
 */
export const materialGroups = (
    filteringRequest: FilteringRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<MaterialGroups>> => {
    
    
    return axios.default.post(
      `/api/storage/materialGroups`,
      filteringRequest,options
    );
  }



/**
 * List MaterialCards. Supports filtering via rsql.
 */
export const materialCards = (
    filteringRequest: FilteringRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<MaterialCards>> => {
    
    
    return axios.default.post(
      `/api/storage/materialCards`,
      filteringRequest,options
    );
  }



/**
 * List Fixture Groups. Supports filtering via rsql.
 */
export const fixtureGroups = (
    filteringRequest: FilteringRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<FixtureGroups>> => {
    
    
    return axios.default.post(
      `/api/storage/fixtureGroups`,
      filteringRequest,options
    );
  }



/**
 * List FixtureCards. Supports filtering via rsql.
 */
export const fixtureCards = (
    filteringRequest: FilteringRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<FixtureCards>> => {
    
    
    return axios.default.post(
      `/api/storage/fixtureCards`,
      filteringRequest,options
    );
  }



/**
 * List AssignmentTransactions. Supports filtering via rsql.
 */
export const assignmentTransactions = (
    filteringRequest: FilteringRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<AssignmentTransactions>> => {
    
    
    return axios.default.post(
      `/api/storage/assignmentTransactions`,
      filteringRequest,options
    );
  }



/**
 * List AssignmentCards. Supports filtering via rsql.
 */
export const assignmentCards = (
    filteringRequest: FilteringRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<AssignmentCards>> => {
    
    
    return axios.default.post(
      `/api/storage/assignmentCards`,
      filteringRequest,options
    );
  }



/**
 * List Proposals. Supports filtering via rsql.
 */
export const proposals = (
    filteringRequest: FilteringRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Proposals>> => {
    
    
    return axios.default.post(
      `/api/sales/proposals`,
      filteringRequest,options
    );
  }



/**
 * List PurchaseOrders. Supports filtering via rsql.
 */
export const purchaseOrders = (
    filteringRequest: FilteringRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PurchaseOrders>> => {
    
    
    return axios.default.post(
      `/api/purchasing/purchaseOrders`,
      filteringRequest,options
    );
  }



/**
 * List Invoices. Supports filtering via rsql.
 */
export const getInvoices = (
    filteringRequest: FilteringRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Invoices>> => {
    
    
    return axios.default.post(
      `/api/purchasing/invoices`,
      filteringRequest,options
    );
  }



/**
 * List Current Accounts. Supports filtering via rsql.
 */
export const currentAccounts = (
    filteringRequest: FilteringRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<CurrentAccounts>> => {
    
    
    return axios.default.post(
      `/api/purchasing/currentAccounts`,
      filteringRequest,options
    );
  }



/**
 * List Current Account Transactions. Supports filtering via rsql.
 */
export const getCurrentAccountTransactions = (
    filteringRequest: FilteringRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<CurrentAccountTransactions>> => {
    
    
    return axios.default.post(
      `/api/purchasing/currentAccountTransactions`,
      filteringRequest,options
    );
  }



/**
 * List CurrentAccountBankAccounts. Supports filtering via rsql.
 */
export const currentAccountBankAccounts = (
    filteringRequest: FilteringRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<CurrentAccountBankAccounts>> => {
    
    
    return axios.default.post(
      `/api/purchasing/currentAccountBankAccounts`,
      filteringRequest,options
    );
  }



/**
 * List AdditionalCosts. Supports filtering via rsql.
 */
export const additionalCosts = (
    filteringRequest: FilteringRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<AdditionalCosts>> => {
    
    
    return axios.default.post(
      `/api/purchasing/additionalCosts`,
      filteringRequest,options
    );
  }



/**
 * List Projects. Supports filtering via rsql.
 */
export const projects = (
    filteringRequest: FilteringRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Projects>> => {
    
    
    return axios.default.post(
      `/api/production/projects`,
      filteringRequest,options
    );
  }



/**
 * List TimeKeepings. Supports filtering via rsql.
 */
export const timeKeepings = (
    filteringRequest: FilteringRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<TimeKeepings>> => {
    
    
    return axios.default.post(
      `/api/hr/timekeepings`,
      filteringRequest,options
    );
  }



/**
 * List Employees. Supports filtering via rsql.
 */
export const employees = (
    filteringRequest: FilteringRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Employees>> => {
    
    
    return axios.default.post(
      `/api/hr/employees`,
      filteringRequest,options
    );
  }



/**
 * List Employee TimeOff Statuses. Supports filtering via rsql.
 */
export const employeeTimeOffStatuses = (
    filteringRequest: FilteringRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<TimeOffStatuses>> => {
    
    
    return axios.default.post(
      `/api/hr/employees/timeoffstatuses`,
      filteringRequest,options
    );
  }



/**
 * List Employee timeoffs. Supports filtering via rsql.
 */
export const timeoffs = (
    id: number,
    filteringRequest: FilteringRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<TimeOffs>> => {
    
    
    return axios.default.post(
      `/api/hr/employee/${id}/timeoffs`,
      filteringRequest,options
    );
  }



/**
 * List Employee - Employee Payments. Supports filtering via rsql.
 */
export const employeePayments = (
    id: number,
    filteringRequest: FilteringRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<EmployeePayments>> => {
    
    
    return axios.default.post(
      `/api/hr/employee/${id}/payments`,
      filteringRequest,options
    );
  }



/**
 * List Employee - Employee Overtimes. Supports filtering via rsql.
 */
export const employeeOvertimes = (
    id: number,
    filteringRequest: FilteringRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<EmployeeOvertimes>> => {
    
    
    return axios.default.post(
      `/api/hr/employee/${id}/overtimes`,
      filteringRequest,options
    );
  }



/**
 * List Banks. Supports filtering via rsql.
 */
export const banks = (
    filteringRequest: FilteringRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Banks>> => {
    
    
    return axios.default.post(
      `/api/finance/banks`,
      filteringRequest,options
    );
  }



/**
 * List Bank Branches. Supports filtering via rsql.
 */
export const bankBranches = (
    filteringRequest: FilteringRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<BankBranches>> => {
    
    
    return axios.default.post(
      `/api/finance/bankBranches`,
      filteringRequest,options
    );
  }



/**
 * List Bank Accounts. Supports filtering via rsql.
 */
export const bankAccounts = (
    filteringRequest: FilteringRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<BankAccounts>> => {
    
    
    return axios.default.post(
      `/api/finance/bankAccounts`,
      filteringRequest,options
    );
  }



/**
 * List Departments. Supports filtering via rsql.
 */
export const departments = (
    filteringRequest: FilteringRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Departments>> => {
    
    
    return axios.default.post(
      `/api/company/departments`,
      filteringRequest,options
    );
  }



/**
 * List Branches. Supports filtering via rsql.
 */
export const branches = (
    filteringRequest: FilteringRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Branches>> => {
    
    
    return axios.default.post(
      `/api/company/branches`,
      filteringRequest,options
    );
  }



/**
 * List Sections. Supports filtering via rsql.
 */
export const sections = (
    filteringRequest: FilteringRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Sections>> => {
    
    
    return axios.default.post(
      `/api/admin/sections`,
      filteringRequest,options
    );
  }



/**
 * List Roles. Supports filtering via rsql.
 */
export const roles = (
    filteringRequest: FilteringRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Roles>> => {
    
    
    return axios.default.post(
      `/api/admin/roles`,
      filteringRequest,options
    );
  }



/**
 * List Public Holidays. Supports filtering via rsql.
 */
export const publicHolidays = (
    filteringRequest: FilteringRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PublicHolidays>> => {
    
    
    return axios.default.post(
      `/api/admin/publicHolidays`,
      filteringRequest,options
    );
  }



/**
 * List PaymentMethods. Supports filtering via rsql.
 */
export const paymentMethods = (
    filteringRequest: FilteringRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<PaymentMethods>> => {
    
    
    return axios.default.post(
      `/api/admin/paymentMethods`,
      filteringRequest,options
    );
  }



/**
 * List Machines. Supports filtering via rsql.
 */
export const machines = (
    filteringRequest: FilteringRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Machines>> => {
    
    
    return axios.default.post(
      `/api/admin/machines`,
      filteringRequest,options
    );
  }



/**
 * List Depots. Supports filtering via rsql.
 */
export const depots = (
    filteringRequest: FilteringRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Depots>> => {
    
    
    return axios.default.post(
      `/api/admin/depots`,
      filteringRequest,options
    );
  }



/**
 * List Companies. Supports filtering via rsql.
 */
export const companies = (
    filteringRequest: FilteringRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<Companies>> => {
    
    
    return axios.default.post(
      `/api/admin/companies`,
      filteringRequest,options
    );
  }



/**
 * List ExpenseInvoices. Supports filtering via rsql.
 */
export const expenseInvoices = (
    filteringRequest: FilteringRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ExpenseInvoices>> => {
    
    
    return axios.default.post(
      `/api/accounting/expenseInvoices`,
      filteringRequest,options
    );
  }



/**
 * List ExpenseCards. Supports filtering via rsql.
 */
export const expenseCards = (
    filteringRequest: FilteringRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<ExpenseCards>> => {
    
    
    return axios.default.post(
      `/api/accounting/expenseCards`,
      filteringRequest,options
    );
  }



/**
 * List CashAccounts. Supports filtering via rsql.
 */
export const cashAccounts = (
    filteringRequest: FilteringRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<CashAccounts>> => {
    
    
    return axios.default.post(
      `/api/accounting/cashAccounts`,
      filteringRequest,options
    );
  }



/**
 * List CashAccountTransactions. Supports filtering via rsql.
 */
export const cashAccountTransactions = (
    filteringRequest: FilteringRequest, options?: AxiosRequestConfig
 ): Promise<AxiosResponse<CashAccountTransactions>> => {
    
    
    return axios.default.post(
      `/api/accounting/cashAccountTransactions`,
      filteringRequest,options
    );
  }



