/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type ActivityTypeEnum = typeof ActivityTypeEnum[keyof typeof ActivityTypeEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ActivityTypeEnum = {
  FinishToStart: 'FinishToStart',
  StartToStart: 'StartToStart',
  FinishToFinish: 'FinishToFinish',
  StartToFinish: 'StartToFinish',
} as const;
