/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { Activity } from './activity';
import type { ActivityTypeEnum } from './activityTypeEnum';
import type { EmployeeExtendedRef } from './employeeExtendedRef';

export interface ActivityConnection {
  /** @nullable */
  id?: number | null;
  previousActivity: Activity;
  nextActivity: Activity;
  type: ActivityTypeEnum;
  description: string;
  delay: number;
  employee: EmployeeExtendedRef;
}
