/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { Activity } from './activity';

export interface Activities {
  message?: string;
  error?: string;
  data?: Activity[];
  total?: number;
  page?: number;
  pageSize?: number;
}
