/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { AssignmentTransaction } from './assignmentTransaction';

export interface AssignmentTransactions {
  message?: string;
  error?: string;
  data?: AssignmentTransaction[];
  total?: number;
  page?: number;
  pageSize?: number;
}
