/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { AssignmentCard } from './assignmentCard';
import type { Employee } from './employee';
import type { AssignmentStatusEnum } from './assignmentStatusEnum';

export interface AssignmentTransaction {
  /** @nullable */
  id?: number | null;
  assignmentCard: AssignmentCard;
  employee: Employee;
  transactionDate: string;
  assignmentStatusEnum: AssignmentStatusEnum;
}
