/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { AssignmentStatusEnum } from './assignmentStatusEnum';
import type { FixtureCard } from './fixtureCard';
import type { Invoice } from './invoice';
import type { WarrantyPeriodEnum } from './warrantyPeriodEnum';
import type { MaintenancePeriodEnum } from './maintenancePeriodEnum';

export interface AssignmentCard {
  /** @nullable */
  id?: number | null;
  assignmentStatusEnum: AssignmentStatusEnum;
  code: string;
  name: string;
  fixtureCard: FixtureCard;
  insuranceCompany: string;
  insurance: boolean;
  insurancePolicyNo: string;
  insuranceDuration: number;
  info: string;
  invoice: Invoice;
  warrantyPeriodEnum: WarrantyPeriodEnum;
  warrantyDay: number;
  underMaintenance: boolean;
  maintenanceDuration: number;
  maintenancePeriodEnum: MaintenancePeriodEnum;
}
