/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { AssignmentCard } from './assignmentCard';

export interface AssignmentCards {
  message?: string;
  error?: string;
  data?: AssignmentCard[];
  total?: number;
  page?: number;
  pageSize?: number;
}
