/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { UserEntity } from './userEntity';
import type { BankEntity } from './bankEntity';

export interface BankBranchEntity {
  id?: number;
  createdAt?: string;
  createdBy?: UserEntity;
  updatedAt?: string;
  deleted?: boolean;
  updatedBy?: UserEntity;
  bank?: BankEntity;
  name?: string;
  relatedEmployee?: string;
}
