/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { UserEntity } from './userEntity';

export interface BankEntity {
  id?: number;
  createdAt?: string;
  createdBy?: UserEntity;
  updatedAt?: string;
  deleted?: boolean;
  updatedBy?: UserEntity;
  /**
   * @minLength 0
   * @maxLength 64
   */
  bankName?: string;
  /**
   * @minLength 0
   * @maxLength 256
   */
  bankShortName?: string;
  /**
   * @minLength 0
   * @maxLength 32
   */
  swiftCode?: string;
}
