/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { Bank } from './bank';

export interface BankBranch {
  /** @nullable */
  id?: number | null;
  bank: Bank;
  name: string;
  relatedEmployee: string;
}
