/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { BankAccount } from './bankAccount';

export interface BankAccounts {
  message?: string;
  error?: string;
  data?: BankAccount[];
  total?: number;
  page?: number;
  pageSize?: number;
}
