/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { BankBranch } from './bankBranch';

export interface BankBranches {
  message?: string;
  error?: string;
  data?: BankBranch[];
  total?: number;
  page?: number;
  pageSize?: number;
}
