/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { BankBranch } from './bankBranch';
import type { BankAccountCurrency } from './bankAccountCurrency';

export interface BankAccount {
  /** @nullable */
  id?: number | null;
  accountNumber: string;
  branch: BankBranch;
  iban: string;
  currency: BankAccountCurrency;
}
