/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type BankAccountCurrency = {
  currencyCode?: string;
  displayName?: string;
  symbol?: string;
  defaultFractionDigits?: number;
  numericCode?: number;
  numericCodeAsString?: string;
};
