/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { UserEntity } from './userEntity';
import type { BankBranchEntity } from './bankBranchEntity';
import type { BankAccountEntityCurrency } from './bankAccountEntityCurrency';

export interface BankAccountEntity {
  id?: number;
  createdAt?: string;
  createdBy?: UserEntity;
  updatedAt?: string;
  deleted?: boolean;
  updatedBy?: UserEntity;
  branch?: BankBranchEntity;
  /**
   * @minLength 0
   * @maxLength 64
   */
  accountNumber?: string;
  /**
   * @minLength 0
   * @maxLength 64
   */
  iban?: string;
  currency?: BankAccountEntityCurrency;
}
