/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { Bank } from './bank';

export interface Banks {
  message?: string;
  error?: string;
  data?: Bank[];
  total?: number;
  page?: number;
  pageSize?: number;
}
