/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface Bank {
  /** @nullable */
  id?: number | null;
  bankName: string;
  bankShortName: string;
  swiftCode?: string;
}
