/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface Branch {
  /** @nullable */
  id?: number | null;
  name: string;
}
