/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { CashAccount } from './cashAccount';
import type { CurrentAccount } from './currentAccount';

export interface CashAccountTransaction {
  /** @nullable */
  id?: number | null;
  date: string;
  cashAccount?: CashAccount;
  currentAccount?: CurrentAccount;
  description: string;
  debtStatus?: boolean;
  total: number;
  balance: number;
}
