/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { CurrencyEnum } from './currencyEnum';

export interface CashAccount {
  /** @nullable */
  id?: number | null;
  code: string;
  name: string;
  currency: CurrencyEnum;
}
