/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { CashAccount } from './cashAccount';

export interface CashAccounts {
  message?: string;
  error?: string;
  data?: CashAccount[];
  total?: number;
  page?: number;
  pageSize?: number;
}
