/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type CashAccountEntityCurrency = typeof CashAccountEntityCurrency[keyof typeof CashAccountEntityCurrency];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CashAccountEntityCurrency = {
  TRY: 'TRY',
  USD: 'USD',
  EUR: 'EUR',
  AUD: 'AUD',
  GBP: 'GBP',
} as const;
