/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { UserEntity } from './userEntity';
import type { CashAccountEntity } from './cashAccountEntity';
import type { CurrentAccountEntity } from './currentAccountEntity';

export interface CashAccountTransactionEntity {
  id?: number;
  createdAt?: string;
  createdBy?: UserEntity;
  updatedAt?: string;
  deleted?: boolean;
  updatedBy?: UserEntity;
  date?: string;
  cashAccount?: CashAccountEntity;
  currentAccount?: CurrentAccountEntity;
  description?: string;
  debtStatus?: boolean;
  total?: number;
  balance?: number;
}
