/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { UserEntity } from './userEntity';
import type { CashAccountEntityCurrency } from './cashAccountEntityCurrency';

export interface CashAccountEntity {
  id?: number;
  createdAt?: string;
  createdBy?: UserEntity;
  updatedAt?: string;
  deleted?: boolean;
  updatedBy?: UserEntity;
  code?: string;
  name?: string;
  currency?: CashAccountEntityCurrency;
}
