/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { Branch } from './branch';

export interface Company {
  /** @nullable */
  id?: number | null;
  code: string;
  title: string;
  address: string;
  phone: string;
  phoneBackup: string;
  taxAdmin: string;
  taxNumber: string;
  branch: Branch;
}
