/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { Company } from './company';

export interface Companies {
  message?: string;
  error?: string;
  data?: Company[];
  total?: number;
  page?: number;
  pageSize?: number;
}
