/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { CurrentAccount } from './currentAccount';

export interface CurrentAccounts {
  message?: string;
  error?: string;
  data?: CurrentAccount[];
  total?: number;
  page?: number;
  pageSize?: number;
}
