/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type CurrentAccountEntitySector = typeof CurrentAccountEntitySector[keyof typeof CurrentAccountEntitySector];


 export const CurrentAccountEntitySector = {
  METAL: 'METAL',
  YACHTING: 'YACHTING',
  ALUMINIUM: 'ALUMINIUM',
  IT: 'IT',
  FOOD: 'FOOD',
} as const;
