/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { CurrentAccount } from './currentAccount';
import type { PaymentTermEnum } from './paymentTermEnum';
import type { CurrencyEnum } from './currencyEnum';

export interface CurrentAccountExtras {
  currentAccount: CurrentAccount;
  paymentTerm: PaymentTermEnum;
  /** Toplam indirim */
  totalDiscount: number;
  currency: CurrencyEnum;
  /** Ek AÃ§Ä±klamalar */
  description?: string;
}
