/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { CurrentAccount } from './currentAccount';
import type { TransactionTypeEnum } from './transactionTypeEnum';
import type { PaymentTypeEnum } from './paymentTypeEnum';
import type { BankAccount } from './bankAccount';
import type { DebtTypeEnum } from './debtTypeEnum';
import type { CurrencyEnum } from './currencyEnum';

export interface CurrentAccountTransaction {
  /** @nullable */
  id?: number | null;
  date: string;
  currentAccount: CurrentAccount;
  /** @nullable */
  description: string | null;
  transactionType: TransactionTypeEnum;
  paymentType: PaymentTypeEnum;
  bankAccount: BankAccount;
  transactionFee: number;
  debtType: DebtTypeEnum;
  amount: number;
  currency: CurrencyEnum;
}
