/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { UserEntity } from './userEntity';
import type { CurrentContactInformationEntityCurrency } from './currentContactInformationEntityCurrency';
import type { CurrentContactInformationEntityAccountType } from './currentContactInformationEntityAccountType';

export interface CurrentContactInformationEntity {
  id?: number;
  createdAt?: string;
  createdBy?: UserEntity;
  updatedAt?: string;
  deleted?: boolean;
  updatedBy?: UserEntity;
  address?: string;
  authorizedPerson?: string;
  faxNo?: string;
  webAddress?: string;
  email?: string;
  specialCode?: string;
  number?: string;
  backupNumber?: string;
  taxAdmin?: string;
  taxNo?: number;
  currency?: CurrentContactInformationEntityCurrency;
  invoicedWithCurrency?: boolean;
  accountType?: CurrentContactInformationEntityAccountType;
}
