/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type CurrencyEnum = typeof CurrencyEnum[keyof typeof CurrencyEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CurrencyEnum = {
  TRY: 'TRY',
  USD: 'USD',
  EUR: 'EUR',
  AUD: 'AUD',
  GBP: 'GBP',
} as const;
