/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type CurrentContactInformationEntityCurrency = typeof CurrentContactInformationEntityCurrency[keyof typeof CurrentContactInformationEntityCurrency];


 export const CurrentContactInformationEntityCurrency = {
  TRY: 'TRY',
  USD: 'USD',
  EUR: 'EUR',
  AUD: 'AUD',
  GBP: 'GBP',
} as const;
