/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { CurrentAccountBankAccount } from './currentAccountBankAccount';

export interface CurrentAccountBankAccounts {
  message?: string;
  error?: string;
  data?: CurrentAccountBankAccount[];
  total?: number;
  page?: number;
  pageSize?: number;
}
