/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type CurrentContactInformationEntityAccountType = typeof CurrentContactInformationEntityAccountType[keyof typeof CurrentContactInformationEntityAccountType];



export const CurrentContactInformationEntityAccountType = {
  CUSTOMER: 'CUSTOMER',
  SELLER: 'SELLER',
  OFFICIAL: 'OFFICIAL',
  RUNNING: 'RUNNING',
} as const;
