/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { CurrencyEnum } from './currencyEnum';
import type { CurrentAccountType } from './currentAccountType';

export interface CurrentContactInformation {
  /** @nullable */
  id?: number | null;
  address: string;
  authorizedPerson: string;
  faxNo: string;
  webAddress?: string;
  email: string;
  specialCode?: string;
  number: string;
  backupNumber?: string;
  taxAdmin: string;
  taxNo: number;
  invoicedWithCurrency: boolean;
  currency: CurrencyEnum;
  accountType: CurrentAccountType;
}
