/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { CurrentAccountTransaction } from './currentAccountTransaction';

export interface CurrentAccountTransactions {
  message?: string;
  error?: string;
  data?: CurrentAccountTransaction[];
  total?: number;
  page?: number;
  pageSize?: number;
}
