/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type CurrentAccountType = typeof CurrentAccountType[keyof typeof CurrentAccountType];


export const CurrentAccountType = {
  CUSTOMER: 'CUSTOMER',
  SELLER: 'SELLER',
  OFFICIAL: 'OFFICIAL',
  RUNNING: 'RUNNING',
} as const;
