/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type CurrentAccountEntitySector = typeof CurrentAccountEntitySector[keyof typeof CurrentAccountEntitySector];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CurrentAccountEntitySector = {
  METAL: 'METAL',
  YACHTING: 'YACHTING',
  ALUMINIUM: 'ALUMINIUM',
  IT: 'IT',
  FOOD: 'FOOD',
} as const;
