/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { UserEntity } from './userEntity';
import type { CurrentAccountEntity } from './currentAccountEntity';
import type { BankEntity } from './bankEntity';
import type { CurrentAccountBankAccountEntityCurrency } from './currentAccountBankAccountEntityCurrency';

export interface CurrentAccountBankAccountEntity {
  id?: number;
  createdAt?: string;
  createdBy?: UserEntity;
  updatedAt?: string;
  deleted?: boolean;
  updatedBy?: UserEntity;
  currentAccount?: CurrentAccountEntity;
  bank?: BankEntity;
  branch?: string;
  /**
   * @minLength 0
   * @maxLength 64
   */
  accountNumber?: string;
  /**
   * @minLength 0
   * @maxLength 64
   */
  iban?: string;
  currency?: CurrentAccountBankAccountEntityCurrency;
}
