/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { CurrentBankAccountRef } from './currentBankAccountRef';
import type { Bank } from './bank';
import type { CurrencyEnum } from './currencyEnum';

export interface CurrentAccountBankAccount {
  /** @nullable */
  id?: number | null;
  currentAccount: CurrentBankAccountRef;
  bank: Bank;
  branch: string;
  accountNumber: string;
  iban: string;
  currency: CurrencyEnum;
}
