/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type DebtTypeEnum = typeof DebtTypeEnum[keyof typeof DebtTypeEnum];


export const DebtTypeEnum = {
  DEBIT: 'DEBIT',
  CREDIT: 'CREDIT',
} as const;
