/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { Department } from './department';

export interface Departments {
  message?: string;
  error?: string;
  data?: Department[];
  total?: number;
  page?: number;
  pageSize?: number;
}
