/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * FiÅŸ tÃ¼rÃ¼
 */
export type DepotTransactionDocumentType = typeof DepotTransactionDocumentType[keyof typeof DepotTransactionDocumentType];


 export const DepotTransactionDocumentType = {
  TRANSFER_INITIALIZATION: 'TRANSFER_INITIALIZATION',
  PROJECT_OUT: 'PROJECT_OUT',
  PROJECT_IN: 'PROJECT_IN',
  TO_PERSONNEL: 'TO_PERSONNEL',
  FROM_PERSONNEL: 'FROM_PERSONNEL',
  INTER_DEPOT: 'INTER_DEPOT',
} as const;
