/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { Depot } from './depot';

export interface Depots {
  message?: string;
  error?: string;
  data?: Depot[];
  total?: number;
  page?: number;
  pageSize?: number;
}
