/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { Employee } from './employee';

export interface Employees {
  message?: string;
  error?: string;
  data?: Employee[];
  total?: number;
  page?: number;
  pageSize?: number;
}
