/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { EmployeePaymentType } from './employeePaymentType';
import type { BankAccount } from './bankAccount';
import type { EmployeePaymentAmountCurrency } from './employeePaymentAmountCurrency';
import type { EmployeeRef } from './employeeRef';

export interface EmployeePayment {
  /** @nullable */
  id?: number | null;
  paymentDate: string;
  paymentType: EmployeePaymentType;
  description: string;
  bankAccount: BankAccount;
  transactionCost: number;
  amount: number;
  amountCurrency: EmployeePaymentAmountCurrency;
  employee?: EmployeeRef;
}
