/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { EmployeeOvertime } from './employeeOvertime';

export interface EmployeeOvertimes {
  message?: string;
  error?: string;
  data?: EmployeeOvertime[];
  total?: number;
  page?: number;
  pageSize?: number;
}
