/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { OverTimePercentage } from './overTimePercentage';
import type { EmployeeRef } from './employeeRef';

export interface EmployeeOvertime {
  /** @nullable */
  id?: number | null;
  description?: string;
  overtimeDate: string;
  workingHours: number;
  overTimePercentage: OverTimePercentage;
  employee?: EmployeeRef;
}
