/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type EmployeePaymentType = typeof EmployeePaymentType[keyof typeof EmployeePaymentType];


export const EmployeePaymentType = {
  SALARY: 'SALARY',
  SALARY_PAYMENT: 'SALARY_PAYMENT',
  OVERTIME: 'OVERTIME',
  ADVANCE: 'ADVANCE',
  DEDUCTION: 'DEDUCTION',
  TRANSFER: 'TRANSFER',
  SEIZURE: 'SEIZURE',
  ADDITIONAL_PAYMENT: 'ADDITIONAL_PAYMENT',
  TRAVEL_PAYMENT: 'TRAVEL_PAYMENT',
} as const;
