/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { EmployeePayment } from './employeePayment';

export interface EmployeePayments {
  message?: string;
  error?: string;
  data?: EmployeePayment[];
  total?: number;
  page?: number;
  pageSize?: number;
}
