/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ErrorResponseFieldErrors } from './errorResponseFieldErrors';

export interface ErrorResponse {
  message?: string;
  error?: string;
  fieldErrors?: ErrorResponseFieldErrors;
}
