/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { Unit } from './unit';

export interface ExpenseCard {
  /** @nullable */
  id?: number | null;
  code: string;
  description: string;
  unit: Unit;
}
