/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ExpenseCard } from './expenseCard';

export interface ExpenseCards {
  message?: string;
  error?: string;
  data?: ExpenseCard[];
  total?: number;
  page?: number;
  pageSize?: number;
}
