/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ExpenseInvoice } from './expenseInvoice';

export interface ExpenseInvoices {
  message?: string;
  error?: string;
  data?: ExpenseInvoice[];
  total?: number;
  page?: number;
  pageSize?: number;
}
