/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ExpenseCard } from './expenseCard';
import type { UnitEnum } from './unitEnum';

export interface ExpenseInvoiceItem {
  /** @nullable */
  id?: number | null;
  expenseCard: ExpenseCard;
  unit: UnitEnum;
  quantity: number;
  price: number;
  discount: number;
  tax: number;
  rowTotal: number;
}
