/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { EmployeeExtendedRef } from './employeeExtendedRef';
import type { BankAccount } from './bankAccount';

/**
 * Proposal Extras
 */
export interface Extras {
  /** @nullable */
  id?: number | null;
  /** Delivery Date */
  deliveryDate: string;
  /** Payment Method */
  paymentMethod: string;
  employee: EmployeeExtendedRef;
  /** Bank Accounts */
  bankAccounts?: BankAccount[];
  /** Technical Details */
  technicalDetails?: string[];
  designFileRequired?: boolean;
  materialRequestRequired?: boolean;
}
