/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type FilteringRequestNamedFiltersItem = typeof FilteringRequestNamedFiltersItem[keyof typeof FilteringRequestNamedFiltersItem];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const FilteringRequestNamedFiltersItem = {
  show_passives: 'show_passives',
} as const;
