/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { FilteringRequestNamedFiltersItem } from './filteringRequestNamedFiltersItem';

/**
 * Filtering request via RSQL. Empty filter returns everything. 

Example filter: (endDate>2023-05-05 and endDate<2024-05-08) and name==Jon 

Example sort: id,asc;company.id,desc
 */
export interface FilteringRequest {
  filter?: string;
  sort?: string;
  /** 0-index page */
  page?: number;
  pageSize?: number;
  namedFilters?: FilteringRequestNamedFiltersItem[];
}
