/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type FixtureTypeEnum = typeof FixtureTypeEnum[keyof typeof FixtureTypeEnum];



export const FixtureTypeEnum = {
  MAIN_MATERIAL: 'MAIN_MATERIAL',
  CONSUMPTION_MATERIAL: 'CONSUMPTION_MATERIAL',
} as const;
