/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { FixtureGroupTreeItem } from './fixtureGroupTreeItem';

export interface FixtureGroupTree {
  fixtureGroups?: FixtureGroupTreeItem[];
}
