/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { FixtureCard } from './fixtureCard';

export interface FixtureCards {
  message?: string;
  error?: string;
  data?: FixtureCard[];
  total?: number;
  page?: number;
  pageSize?: number;
}
