/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { FixtureGroup } from './fixtureGroup';

export interface FixtureGroups {
  message?: string;
  error?: string;
  data?: FixtureGroup[];
  total?: number;
  page?: number;
  pageSize?: number;
}
