/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { WarehouseBranchEnum } from './warehouseBranchEnum';
import type { CurrencyEnum } from './currencyEnum';
import type { InvoiceItem } from './invoiceItem';
import type { InvoiceTypeEnum } from './invoiceTypeEnum';

export interface Invoice {
  /** @nullable */
  id?: number | null;
  code: string;
  date: string;
  warehouseBranch: WarehouseBranchEnum;
  specialCode?: string;
  currency: CurrencyEnum;
  fixedCurrency: boolean;
  fixedCurrencyValue: number;
  invoiceItems: InvoiceItem[];
  generalDiscount: number;
  unitDiscount: number;
  totalVat: number;
  totalAdditionalCosts: number;
  subTotal: number;
  finalTotal: number;
  invoiceTypeEnum: InvoiceTypeEnum;
}
