/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { InvoiceItemTypeEnum } from './invoiceItemTypeEnum';
import type { UnitEnum } from './unitEnum';

export interface InvoiceItem {
  /** @nullable */
  id?: number | null;
  invoiceItemType: InvoiceItemTypeEnum;
  invoiceItemTypeEntityId: string;
  code: string;
  name: string;
  unit: UnitEnum;
  quantity: number;
  price: number;
  discount: number;
  tax: number;
  rowTotal: number;
}
