/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type InvoiceItemTypeEnum = typeof InvoiceItemTypeEnum[keyof typeof InvoiceItemTypeEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const InvoiceItemTypeEnum = {
  ADDITIONAL_COST: 'ADDITIONAL_COST',
  SERVICE: 'SERVICE',
  MATERIAL: 'MATERIAL',
  FIXTURE: 'FIXTURE',
} as const;
