/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type InvoiceTypeEnum = typeof InvoiceTypeEnum[keyof typeof InvoiceTypeEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const InvoiceTypeEnum = {
  RECEIPT_INVOICE: 'RECEIPT_INVOICE',
  RETURN_INVOICE: 'RETURN_INVOICE',
} as const;
