/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { Invoice } from './invoice';

export interface Invoices {
  message?: string;
  error?: string;
  data?: Invoice[];
  total?: number;
  page?: number;
  pageSize?: number;
}
