/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { EmployeeExtendedRef } from './employeeExtendedRef';

/**
 * Proposal Labor Cost Items
 */
export interface LaborCost {
  /** @nullable */
  id?: number | null;
  employee?: EmployeeExtendedRef;
  /** Description */
  description?: string;
  /** Man / Hour */
  manHour?: number;
  /** Man Hour Cost */
  manHourCost?: number;
  /** Cost */
  cost?: number;
}
