/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { EmployeeExtendedRef } from './employeeExtendedRef';

export interface Machine {
  /** @nullable */
  id?: number | null;
  code: string;
  description: string;
  employee: EmployeeExtendedRef;
}
