/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { Employee } from './employee';

export interface Machine {
  /** @nullable */
  id?: number | null;
  code: string;
  description: string;
  employee: Employee;
}
