/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type MaintenancePeriodEnum = typeof MaintenancePeriodEnum[keyof typeof MaintenancePeriodEnum];


 export const MaintenancePeriodEnum = {
  DAY: 'DAY',
  WEEK: 'WEEK',
  MONTH: 'MONTH',
  YEAR: 'YEAR',
} as const;
