/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * YÃ¶nlendirme tipi (SATIN ALMA / DEPO)
 */
export type MaterialRequestFulfillmentRoutingType = typeof MaterialRequestFulfillmentRoutingType[keyof typeof MaterialRequestFulfillmentRoutingType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MaterialRequestFulfillmentRoutingType = {
  PROCUREMENT: 'PROCUREMENT',
  WAREHOUSE: 'WAREHOUSE',
  MATERIAL_REQUEST: 'MATERIAL_REQUEST',
} as const;
