/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { MaterialRequestFulfillmentRoutingType } from './materialRequestFulfillmentRoutingType';
import type { MaterialRequest } from './materialRequest';

export interface MaterialRequestFulfillment {
  /** @nullable */
  id?: number | null;
  /** YÃ¶nlendirme tipi (SATIN ALMA / DEPO) */
  routingType: MaterialRequestFulfillmentRoutingType;
  materialRequest: MaterialRequest;
  /** Bekleyen miktar (talep - karÅŸÄ±lanan - stok) */
  pending: number;
  /** KarÅŸÄ±lanan miktar */
  fulfilled: number;
  /** Depo mevcut bakiyesi */
  stockBalance: number;
}
