/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * BÃ¶lÃ¼m onay durumu
 */
export type MaterialRequestRowItemSectionApprovalEnum = typeof MaterialRequestRowItemSectionApprovalEnum[keyof typeof MaterialRequestRowItemSectionApprovalEnum];


 export const MaterialRequestRowItemSectionApprovalEnum = {
  PENDING_APPROVAL: 'PENDING_APPROVAL',
  APPROVED: 'APPROVED',
  PARTIALLY_APPROVED: 'PARTIALLY_APPROVED',
  REJECTED: 'REJECTED',
  INCORRECT_INFORMATION: 'INCORRECT_INFORMATION',
} as const;
