/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { MaterialRequest } from './materialRequest';

export interface MaterialRequests {
  message?: string;
  error?: string;
  data?: MaterialRequest[];
  total?: number;
  page?: number;
  pageSize?: number;
}
