/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { MaterialGroupTreeItem } from './materialGroupTreeItem';

export interface MaterialGroupTree {
  message?: string;
  error?: string;
  materialGroups?: MaterialGroupTreeItem[];
}
