/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { UnitEnum } from './unitEnum';

/**
 * @nullable
 */
export type MaterialCardUnit = {
  /** @nullable */
  id?: number | null;
  unit: UnitEnum;
  multiplier: number;
} | null;
