/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type MaterialTypeEnum = typeof MaterialTypeEnum[keyof typeof MaterialTypeEnum];



export const MaterialTypeEnum = {
  MAIN_MATERIAL: 'MAIN_MATERIAL',
  CONSUMPTION_MATERIAL: 'CONSUMPTION_MATERIAL',
} as const;
