/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { MaterialGroupRef } from './materialGroupRef';
import type { UnitEnum } from './unitEnum';
import type { MaterialTypeEnum } from './materialTypeEnum';
import type { MaterialCardUnit } from './materialCardUnit';

export interface MaterialCard {
  /** @nullable */
  id?: number | null;
  materialCode: string;
  materialName: string;
  materialGroup: MaterialGroupRef;
  defaultUnit: UnitEnum;
  materialType: MaterialTypeEnum;
  /** @nullable */
  optimalLevel?: number | null;
  /** @nullable */
  minimumLevel?: number | null;
  /** @nullable */
  specialCode?: string | null;
  /** @nullable */
  shelfLocation?: string | null;
  /** @nullable */
  materialCardUnits?: MaterialCardUnit[] | null;
}
