/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { MaterialCard } from './materialCard';

export interface MaterialCards {
  message?: string;
  error?: string;
  data?: MaterialCard[];
  total?: number;
  page?: number;
  pageSize?: number;
}
