/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { MaterialRequestRowItemSectionApprovalEnum } from './materialRequestRowItemSectionApprovalEnum';
import type { MaterialCard } from './materialCard';
import type { MaterialRequestRowItemUnit } from './materialRequestRowItemUnit';

/**
 * Talep edilen malzemelerin listesi
 */
export interface MaterialRequestRowItem {
  /** BÃ¶lÃ¼m onay durumu */
  sectionApprovalEnum?: MaterialRequestRowItemSectionApprovalEnum;
  materialCard: MaterialCard;
  /** Belirtilen detaylar */
  specify?: string;
  /** Talep edilen miktar */
  quantity: number;
  /** Birim tÃ¼rÃ¼ */
  unit: MaterialRequestRowItemUnit;
  /** Notlar */
  notes?: string;
  /** Sertifika bilgisi */
  certificate?: string;
  /** Kalite belgesi */
  qualityDocument?: string;
  qualityControl?: boolean;
}
