/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { MaterialGroupTreeItem } from './materialGroupTreeItem';

export interface MaterialGroupTreeDataResponse {
  message?: string;
  error?: string;
  data?: MaterialGroupTreeItem[];
  total?: number;
  page?: number;
  pageSize?: number;
}
