/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * Birim tÃ¼rÃ¼
 */
export type MaterialRequestRowItemUnit = typeof MaterialRequestRowItemUnit[keyof typeof MaterialRequestRowItemUnit];


export const MaterialRequestRowItemUnit = {
  KG: 'KG',
  GR: 'GR',
  METER: 'METER',
  M2: 'M2',
  M3: 'M3',
  LITRE: 'LITRE',
  PIECE: 'PIECE',
  PACKAGE: 'PACKAGE',
  PAIR: 'PAIR',
  PLATE: 'PLATE',
  MM: 'MM',
} as const;
