/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { MaterialRequestFulfillment } from './materialRequestFulfillment';

export interface MaterialRequestFulfillments {
  message?: string;
  error?: string;
  data?: MaterialRequestFulfillment[];
  total?: number;
  page?: number;
  pageSize?: number;
}
