/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type MaterialTypeEnum = typeof MaterialTypeEnum[keyof typeof MaterialTypeEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MaterialTypeEnum = {
  MAIN_MATERIAL: 'MAIN_MATERIAL',
  CONSUMPTION_MATERIAL: 'CONSUMPTION_MATERIAL',
} as const;
