/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { MaterialRequestRowItem } from './materialRequestRowItem';
import type { CurrencyEnum } from './currencyEnum';

export interface MaterialRequestExtras {
  /** @nullable */
  id?: number | null;
  materialRequestRowItem: MaterialRequestRowItem;
  /**
   * Birim fiyat
   * @nullable
   */
  price: number | null;
  /**
   * Ä°ndirim oranÄ± veya tutarÄ±
   * @nullable
   */
  discount?: number | null;
  /**
   * Vergi oranÄ±
   * @nullable
   */
  taxRate: number | null;
  /**
   * Vergi tutarÄ±
   * @nullable
   */
  tax: number | null;
  /**
   * SatÄ±r toplam tutarÄ± (vergi ve indirim dahil)
   * @nullable
   */
  rowTotal: number | null;
  currency: CurrencyEnum;
  /**
   * Montaj maliyeti
   * @nullable
   */
  assemblyCost: number | null;
  /**
   * Sertifika maliyeti
   * @nullable
   */
  certificateCost?: number | null;
  /**
   * Ä°lgili satÄ±r iÃ§in talep tarihi
   * @nullable
   */
  requestDateRow: string | null;
}
