/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type OverTimePercentage = typeof OverTimePercentage[keyof typeof OverTimePercentage];


 export const OverTimePercentage = {
  P50: 'P50',
  P100: 'P100',
  P150: 'P150',
  P200: 'P200',
} as const;
