/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type PaymentTypeEnum = typeof PaymentTypeEnum[keyof typeof PaymentTypeEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PaymentTypeEnum = {
  NO_PAYMENT: 'NO_PAYMENT',
  CASH: 'CASH',
  CHECK: 'CHECK',
  BOND: 'BOND',
  EFT: 'EFT',
  BANK_CARD: 'BANK_CARD',
} as const;
