/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * Ã–deme vadesi
 */
export type PaymentTermEnum = typeof PaymentTermEnum[keyof typeof PaymentTermEnum];


 export const PaymentTermEnum = {
  CASH: 'CASH',
  DUE_IN_15_DAYS: 'DUE_IN_15_DAYS',
  DUE_IN_30_DAYS: 'DUE_IN_30_DAYS',
  ON_DELIVERY: 'ON_DELIVERY',
  ON_ORDER: 'ON_ORDER',
  INSTALLMENT: 'INSTALLMENT',
} as const;
