/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * @nullable
 */
export type PayrollData = {
  /** @nullable */
  id?: number | null;
  /** @nullable */
  currency?: string | null;
  salary: number;
  /** @nullable */
  includedInCost?: boolean | null;
  /** @nullable */
  monthlyProgress?: number | null;
  /** @nullable */
  monthlyHour?: number | null;
  iban: string;
  /**
   * @minimum 0
   * @nullable
   */
  children?: number | null;
  spouseWorking?: boolean;
} | null;
