/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type PlanStatusEnum = typeof PlanStatusEnum[keyof typeof PlanStatusEnum];


export const PlanStatusEnum = {
  PLANNED: 'PLANNED',
  STARTED: 'STARTED',
  COMPLETED: 'COMPLETED',
} as const;
