/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ProductionPlanProduct } from './productionPlanProduct';

export interface ProductionPlanProducts {
  message?: string;
  error?: string;
  data?: ProductionPlanProduct[];
  total?: number;
  page?: number;
  pageSize?: number;
}
