/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ProductCard } from './productCard';

export interface ProductionPlanProduct {
  /** @nullable */
  id?: number | null;
  quantity: number;
  productCard: ProductCard;
}
