/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * Product Card
 */
export interface ProductCardRef {
  /** @nullable */
  id?: number | null;
}
