/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ProductCardRef } from './productCardRef';

/**
 * @nullable
 */
export type ProductCardUnit = {
  /** @nullable */
  id?: number | null;
  productCard: ProductCardRef;
  multiplier: number;
} | null;
