/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ProductGroup } from './productGroup';

export interface ProductGroups {
  message?: string;
  error?: string;
  data?: ProductGroup[];
  total?: number;
  page?: number;
  pageSize?: number;
}
