/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ProductCardRef } from './productCardRef';

/**
 * Proposal Product Rows
 */
export interface ProductRowItem {
  /** @nullable */
  id?: number | null;
  productCard: ProductCardRef;
  /** Discount */
  discount: number;
  /** Expense */
  expense: number;
  /** Profit */
  profit: number;
  /** Profit Margin % */
  profitMargin: number;
  /** Price */
  price: number;
  /** Row Total */
  rowTotal?: number;
}
