/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ProductPlan } from './productPlan';

export interface ProductPlans {
  message?: string;
  error?: string;
  data?: ProductPlan[];
  total?: number;
  page?: number;
  pageSize?: number;
}
