/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type ProductTypeEnum = typeof ProductTypeEnum[keyof typeof ProductTypeEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ProductTypeEnum = {
  PRODUCT: 'PRODUCT',
  SEMI_PRODUCT: 'SEMI_PRODUCT',
} as const;
