/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ProductCard } from './productCard';

export interface ProductCards {
  message?: string;
  error?: string;
  data?: ProductCard[];
  total?: number;
  page?: number;
  pageSize?: number;
}
