/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ProductGroupTreeItem } from './productGroupTreeItem';

export interface ProductGroupTreeDataResponse {
  message?: string;
  error?: string;
  data?: ProductGroupTreeItem[];
  total?: number;
  page?: number;
  pageSize?: number;
}
