/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { CurrentAccount } from './currentAccount';
import type { Employee } from './employee';

export interface Project {
  /** @nullable */
  id?: number | null;
  currentAccount: CurrentAccount;
  code: string;
  name: string;
  employee: Employee;
}
