/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { Project } from './project';

export interface Projects {
  message?: string;
  error?: string;
  data?: Project[];
  total?: number;
  page?: number;
  pageSize?: number;
}
