/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ProposalRequest } from './proposalRequest';

export interface ProposalRequests {
  message?: string;
  error?: string;
  data?: ProposalRequest[];
  total?: number;
  page?: number;
  pageSize?: number;
}
