/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { Proposal } from './proposal';

export interface Proposals {
  message?: string;
  error?: string;
  data?: Proposal[];
  total?: number;
  page?: number;
  pageSize?: number;
}
