/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface ProposalRequestCalculationResult {
  total: number;
  totalDiscount: number;
  unitDiscount: number;
  additionalCost: number;
  tax: number;
}
