/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * Purchase Order Name
 */
export type ProposalStateEnum = typeof ProposalStateEnum[keyof typeof ProposalStateEnum];


export const ProposalStateEnum = {
  CREATED: 'CREATED',
  FORWARDED_TO_CUSTOMER: 'FORWARDED_TO_CUSTOMER',
  CUSTOMER_ACCEPTED: 'CUSTOMER_ACCEPTED',
  CUSTOMER_PARTIALLY_ACCEPTED: 'CUSTOMER_PARTIALLY_ACCEPTED',
  PRODUCTION_STARTED: 'PRODUCTION_STARTED',
  CUSTOMER_REJECTED: 'CUSTOMER_REJECTED',
  CANCELLED: 'CANCELLED',
  DELIVERED: 'DELIVERED',
} as const;
