/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ProposalStateEnum } from './proposalStateEnum';
import type { CurrentAccount } from './currentAccount';
import type { ProductRowItem } from './productRowItem';
import type { LaborCost } from './laborCost';
import type { MaterialCard } from './materialCard';
import type { Extras } from './extras';

export interface Proposal {
  /** @nullable */
  id?: number | null;
  /** Purchase Order Date */
  date: string;
  proposalState: ProposalStateEnum;
  /** Proposal Number */
  proposalNo: string;
  currentAccount: CurrentAccount;
  /** Proposal Discount */
  discount: number;
  /** Proposal Expense */
  expense: number;
  /** Proposal Tax */
  tax: number;
  /** Proposal Total */
  total: number;
  /** Proposal Description */
  description: string;
  /** Proposal Product Rows */
  products: ProductRowItem[];
  /** Proposal Labor Cost Items */
  laborCosts?: LaborCost[];
  materialCards?: MaterialCard[];
  /** Proposal Unit Discount */
  unitDiscount: number;
  /** Proposal Total Tax */
  totalTax: number;
  /** Proposal Additional Costs */
  additionalCosts: number;
  /** Proposal Final Total */
  finalTotal: number;
  extras: Extras;
}
