/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { PublicHoliday } from './publicHoliday';

export interface PublicHolidays {
  message?: string;
  error?: string;
  data?: PublicHoliday[];
  total?: number;
  page?: number;
  pageSize?: number;
}
