/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface PublicHoliday {
  /** @nullable */
  id?: number | null;
  year: number;
  startDate: string;
  endDate: string;
  /** @nullable */
  description?: string | null;
}
