/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type PurchaseOrderItemUnit = typeof PurchaseOrderItemUnit[keyof typeof PurchaseOrderItemUnit];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const PurchaseOrderItemUnit = {
  KG: 'KG',
  GR: 'GR',
  METER: 'METER',
  M2: 'M2',
  M3: 'M3',
  LITRE: 'LITRE',
  PIECE: 'PIECE',
  PACKAGE: 'PACKAGE',
  PAIR: 'PAIR',
  PLATE: 'PLATE',
  MM: 'MM',
} as const;
