/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { MaterialCard } from './materialCard';
import type { PurchaseOrderItemUnit } from './purchaseOrderItemUnit';

/**
 * Purchase Order Items
 */
export interface PurchaseOrderItem {
  /** @nullable */
  id?: number | null;
  materialCard: MaterialCard;
  quantity: number;
  unit: PurchaseOrderItemUnit;
}
