/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { EmployeeExtendedRef } from './employeeExtendedRef';
import type { Project } from './project';
import type { CurrentAccount } from './currentAccount';
import type { PurchaseOrderItem } from './purchaseOrderItem';

export interface PurchaseOrder {
  /** Purchase Order ID */
  id?: number;
  /** Purchase Order Date */
  date: string;
  /** Purchase Order Name */
  name: string;
  employee: EmployeeExtendedRef;
  /** Purchase Order Description */
  description: string;
  project: Project;
  currentAccount: CurrentAccount;
  /** Purchase Order Items */
  purchaseOrderItems?: PurchaseOrderItem[];
}
