/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { PurchaseOrder } from './purchaseOrder';

export interface PurchaseOrders {
  message?: string;
  error?: string;
  data?: PurchaseOrder[];
  total?: number;
  page?: number;
  pageSize?: number;
}
