/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { Role } from './role';

export interface Roles {
  message?: string;
  error?: string;
  data?: Role[];
  total?: number;
  page?: number;
  pageSize?: number;
}
