/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { Section } from './section';

export interface Sections {
  message?: string;
  error?: string;
  data?: Section[];
  total?: number;
  page?: number;
  pageSize?: number;
}
