/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { SectionTypeEnum } from './sectionTypeEnum';
import type { EmployeeExtendedRef } from './employeeExtendedRef';

export interface Section {
  /** @nullable */
  id?: number | null;
  name: string;
  sectionType: SectionTypeEnum;
  employee: EmployeeExtendedRef;
}
