/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type SectionTypeEnum = typeof SectionTypeEnum[keyof typeof SectionTypeEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SectionTypeEnum = {
  MANAGEMENT: 'MANAGEMENT',
  IT: 'IT',
  PRODUCTION: 'PRODUCTION',
  FINANCE: 'FINANCE',
  DESIGN: 'DESIGN',
  ACCOUNTING: 'ACCOUNTING',
  PURCHASING: 'PURCHASING',
} as const;
