/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type SectorEnum = typeof SectorEnum[keyof typeof SectorEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const SectorEnum = {
  METAL: 'METAL',
  YACHTING: 'YACHTING',
  ALUMINIUM: 'ALUMINIUM',
  IT: 'IT',
  FOOD: 'FOOD',
} as const;
