/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface ServiceCards {
  message?: string;
  error?: string;
  data?: ServiceCards[];
  total?: number;
  page?: number;
  pageSize?: number;
}
