/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ServiceGroupTreeItem } from './serviceGroupTreeItem';

export interface ServiceGroupTree {
  serviceGroups?: ServiceGroupTreeItem[];
}
