/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { UnitEnum } from './unitEnum';

/**
 * @nullable
 */
export type ServiceCardUnit = {
  /** @nullable */
  id?: number | null;
  unit: UnitEnum;
  multiplier: number;
} | null;
