/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ServiceGroup } from './serviceGroup';

export interface ServiceGroups {
  message?: string;
  error?: string;
  data?: ServiceGroup[];
  total?: number;
  page?: number;
  pageSize?: number;
}
