/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type ServiceTypeEnum = typeof ServiceTypeEnum[keyof typeof ServiceTypeEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ServiceTypeEnum = {
  MAIN_SERVICE: 'MAIN_SERVICE',
  CONSUMPTION_SERVICE: 'CONSUMPTION_SERVICE',
} as const;
