/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export interface ServiceGroup {
  /** @nullable */
  id?: number | null;
  name: string;
  code: string;
  parent?: ServiceGroup;
}
