/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { Shelf } from './shelf';

export interface Shelves {
  message?: string;
  error?: string;
  data?: Shelf[];
  total?: number;
  page?: number;
  pageSize?: number;
}
