/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { TimeKeeping } from './timeKeeping';

export interface TimeKeepings {
  message?: string;
  error?: string;
  data?: TimeKeeping[];
  total?: number;
  page?: number;
  pageSize?: number;
}
