/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { TimeOffStatus } from './timeOffStatus';

export interface TimeOffStatuses {
  message?: string;
  error?: string;
  data?: TimeOffStatus[];
  total?: number;
  page?: number;
  pageSize?: number;
}
