/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { TimeOffType } from './timeOffType';

export interface TimeOff {
  /** @nullable */
  id?: number | null;
  startDateTime: string;
  endDateTime: string;
  workingDays: number;
  workingHours: number;
  timeOffType: TimeOffType;
  unPaid?: boolean;
}
