/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type TimeOffType = typeof TimeOffType[keyof typeof TimeOffType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TimeOffType = {
  SICK_LEAVE: 'SICK_LEAVE',
  VACATION: 'VACATION',
  ON_DEMAND: 'ON_DEMAND',
  MARRIAGE: 'MARRIAGE',
  CHILD_BIRTH: 'CHILD_BIRTH',
} as const;
