/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { EmployeeRef } from './employeeRef';

/**
 * Represents calculated time off status (izin durumu) for an employee.
 */
export interface TimeOffStatus {
  entitled: number;
  allTimeUsed: number;
  employee: EmployeeRef;
  transferred: number;
  /** For display only, no id returned */
  usedCurrentYear: number;
  usable: number;
  profession: string;
  startDateTime?: string;
  workingDays: number;
}
