/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { TimeOff } from './timeOff';

export interface TimeOffs {
  message?: string;
  error?: string;
  data?: TimeOff[];
  total?: number;
  page?: number;
  pageSize?: number;
}
