/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type TransactionTypeEnum = typeof TransactionTypeEnum[keyof typeof TransactionTypeEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const TransactionTypeEnum = {
  ORDER: 'ORDER',
  INVOICE: 'INVOICE',
  PAYMENT: 'PAYMENT',
  COLLECTION: 'COLLECTION',
  EXPENSE: 'EXPENSE',
  EMPLOYEE_ADVANCE: 'EMPLOYEE_ADVANCE',
  EMPLOYEE_SALARY: 'EMPLOYEE_SALARY',
  TAX: 'TAX',
  SOCIAL_SECURITY: 'SOCIAL_SECURITY',
  FREELANCE_RECEIPT: 'FREELANCE_RECEIPT',
  RENT: 'RENT',
  TRANSFER: 'TRANSFER',
  DOCUMENT_CANCELLATION: 'DOCUMENT_CANCELLATION',
} as const;
