/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { User } from './user';

export interface Users {
  message?: string;
  error?: string;
  data?: User[];
  total?: number;
  page?: number;
  pageSize?: number;
}
