/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

/**
 * @deprecated
 */
export type UserRole = typeof UserRole[keyof typeof UserRole];


 export const UserRole = {
  USER: 'USER',
  ADMIN: 'ADMIN',
} as const;
