/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { UserEntityRole } from './userEntityRole';

export interface UserEntity {
  id?: number;
  createdAt?: string;
  createdBy?: UserEntity;
  updatedAt?: string;
  deleted?: boolean;
  updatedBy?: UserEntity;
  email?: string;
  password?: string;
  role?: UserEntityRole;
}
