/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { UserRolesResponseDataItem } from './userRolesResponseDataItem';

export interface UserRolesResponse {
  message?: string;
  error?: string;
  data?: UserRolesResponseDataItem[];
  total?: number;
  page?: number;
  pageSize?: number;
}
