/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type UserEntityRole = typeof UserEntityRole[keyof typeof UserEntityRole];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserEntityRole = {
  USER: 'USER',
  ADMIN: 'ADMIN',
} as const;
