/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { UserEntityRole } from './userEntityRole';
import type { UserEntityUserRolesItem } from './userEntityUserRolesItem';

export interface UserEntity {
  id?: number;
  createdAt?: string;
  createdBy?: UserEntity;
  updatedAt?: string;
  deleted?: boolean;
  updatedBy?: UserEntity;
  email?: string;
  password?: string;
  role?: UserEntityRole;
  userRoles?: UserEntityUserRolesItem[];
  active?: boolean;
}
