/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { UserAddUserRolesItem } from './userAddUserRolesItem';

export interface UserAdd {
  email: string;
  active?: boolean;
  /**
   * @minLength 8
   * @maxLength 64
   */
  userPassword: string;
  /**
   * @minLength 8
   * @maxLength 64
   */
  userPassword2: string;
  userRoles?: UserAddUserRolesItem[];
}
