/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type UserRolesRequestUserRolesItem = typeof UserRolesRequestUserRolesItem[keyof typeof UserRolesRequestUserRolesItem];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const UserRolesRequestUserRolesItem = {
  ROLE_ACCOUNTING_ADMIN: 'ROLE_ACCOUNTING_ADMIN',
  ROLE_COMPANY_ADMIN: 'ROLE_COMPANY_ADMIN',
  ROLE_FINANCE_ADMIN: 'ROLE_FINANCE_ADMIN',
  ROLE_HR_ADMIN: 'ROLE_HR_ADMIN',
  ROLE_PRODUCTION_ADMIN: 'ROLE_PRODUCTION_ADMIN',
  ROLE_PURCHASING_ADMIN: 'ROLE_PURCHASING_ADMIN',
  ROLE_SALES_ADMIN: 'ROLE_SALES_ADMIN',
  ROLE_STORAGE_ADMIN: 'ROLE_STORAGE_ADMIN',
  ROLE_ERP_ADMIN: 'ROLE_ERP_ADMIN',
  ROLE_PLANNING_ADMIN: 'ROLE_PLANNING_ADMIN',
  ROLE_GENERAL_ADMIN: 'ROLE_GENERAL_ADMIN',
} as const;
