/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type WarehouseBranchEnum = typeof WarehouseBranchEnum[keyof typeof WarehouseBranchEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const WarehouseBranchEnum = {
  DUZCE: 'DUZCE',
  TUZLA: 'TUZLA',
  TERSANE: 'TERSANE',
} as const;
