/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type WarehouseBranchEnum = typeof WarehouseBranchEnum[keyof typeof WarehouseBranchEnum];


 export const WarehouseBranchEnum = {
  DUZCE: 'DUZCE',
  TUZLA: 'TUZLA',
  TERSANE: 'TERSANE',
} as const;
