/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type WarrantyPeriodEnum = typeof WarrantyPeriodEnum[keyof typeof WarrantyPeriodEnum];


export const WarrantyPeriodEnum = {
  DAY: 'DAY',
  WEEK: 'WEEK',
  MONTH: 'MONTH',
  YEAR: 'YEAR',
} as const;
