/**
 * Generated by orval v7.7.0 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */

export type WarrantyPeriodEnum = typeof WarrantyPeriodEnum[keyof typeof WarrantyPeriodEnum];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const WarrantyPeriodEnum = {
  DAY: 'DAY',
  WEEK: 'WEEK',
  MONTH: 'MONTH',
  YEAR: 'YEAR',
} as const;
