/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { ProductPlan } from './productPlan';

export interface Wbs {
  /** @nullable */
  id?: number | null;
  ownerPlan: ProductPlan;
}
