/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { Wbs } from './wbs';

export interface WBSList {
  message?: string;
  error?: string;
  data?: Wbs[];
  total?: number;
  page?: number;
  pageSize?: number;
}
