/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { WorkOrderConnection } from './workOrderConnection';

export interface WorkOrderConnections {
  message?: string;
  error?: string;
  data?: WorkOrderConnection[];
  total?: number;
  page?: number;
  pageSize?: number;
}
