/**
 * Generated by orval v7.4.1 🍺
 * Do not edit manually.
 * OpenAPI definition
 * OpenAPI spec version: v0
 */
import type { WorkOrder } from './workOrder';
import type { ActivityTypeEnum } from './activityTypeEnum';
import type { EmployeeExtendedRef } from './employeeExtendedRef';

export interface WorkOrderConnection {
  /** @nullable */
  id?: number | null;
  previousWorkOrder: WorkOrder;
  nextWorkOrder: WorkOrder;
  type: ActivityTypeEnum;
  description: string;
  delay: number;
  employee: EmployeeExtendedRef;
}
