/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as LoginImport } from './routes/login'
import { Route as AuthenticatedImport } from './routes/_authenticated'
import { Route as IndexImport } from './routes/index'
import { Route as AuthenticatedHrImport } from './routes/_authenticated/hr'
import { Route as AuthenticatedDashboardImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedHrIndexImport } from './routes/_authenticated/hr/index'
import { Route as AuthenticatedHrVacationsImport } from './routes/_authenticated/hr/vacations'
import { Route as AuthenticatedHrTimekeepingImport } from './routes/_authenticated/hr/timekeeping'
import { Route as AuthenticatedHrFinancesImport } from './routes/_authenticated/hr/finances'
import { Route as AuthenticatedHrEmployeesImport } from './routes/_authenticated/hr/employees'
import { Route as AuthenticatedHrDebitCreditAnalysisImport } from './routes/_authenticated/hr/debitCreditAnalysis'
import { Route as AuthenticatedHrVacationsIndexImport } from './routes/_authenticated/hr/vacations/index'
import { Route as AuthenticatedHrTimekeepingIndexImport } from './routes/_authenticated/hr/timekeeping/index'
import { Route as AuthenticatedHrFinancesIndexImport } from './routes/_authenticated/hr/finances/index'
import { Route as AuthenticatedHrEmployeesIndexImport } from './routes/_authenticated/hr/employees/index'
import { Route as AuthenticatedAccountingCashAccountsIndexImport } from './routes/_authenticated/accounting/cashAccounts/index'
import { Route as AuthenticatedHrVacationsNewImport } from './routes/_authenticated/hr/vacations/new'
import { Route as AuthenticatedHrTimekeepingNewImport } from './routes/_authenticated/hr/timekeeping/new'
import { Route as AuthenticatedHrEmployeesNewImport } from './routes/_authenticated/hr/employees/new'
import { Route as AuthenticatedAccountingCashAccountsNewImport } from './routes/_authenticated/accounting/cashAccounts/new'
import { Route as AuthenticatedHrTimekeepingIdIndexImport } from './routes/_authenticated/hr/timekeeping/$id/index'
import { Route as AuthenticatedHrEmployeesIdIndexImport } from './routes/_authenticated/hr/employees/$id/index'
import { Route as AuthenticatedAccountingCashAccountsIdIndexImport } from './routes/_authenticated/accounting/cashAccounts/$id/index'
import { Route as AuthenticatedHrVacationsNewIdImport } from './routes/_authenticated/hr/vacations/new/$id'

// Create/Update Routes

const LoginRoute = LoginImport.update({
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedRoute = AuthenticatedImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const AuthenticatedHrRoute = AuthenticatedHrImport.update({
  path: '/hr',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedDashboardRoute = AuthenticatedDashboardImport.update({
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedAdminRoute = AuthenticatedAdminImport.update({
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)

const AuthenticatedHrIndexRoute = AuthenticatedHrIndexImport.update({
  path: '/',
  getParentRoute: () => AuthenticatedHrRoute,
} as any)

const AuthenticatedHrVacationsRoute = AuthenticatedHrVacationsImport.update({
  path: '/vacations',
  getParentRoute: () => AuthenticatedHrRoute,
} as any)

const AuthenticatedHrTimekeepingRoute = AuthenticatedHrTimekeepingImport.update(
  {
    path: '/timekeeping',
    getParentRoute: () => AuthenticatedHrRoute,
  } as any,
)

const AuthenticatedHrFinancesRoute = AuthenticatedHrFinancesImport.update({
  path: '/finances',
  getParentRoute: () => AuthenticatedHrRoute,
} as any)

const AuthenticatedHrEmployeesRoute = AuthenticatedHrEmployeesImport.update({
  path: '/employees',
  getParentRoute: () => AuthenticatedHrRoute,
} as any)

const AuthenticatedHrDebitCreditAnalysisRoute =
  AuthenticatedHrDebitCreditAnalysisImport.update({
    path: '/debitCreditAnalysis',
    getParentRoute: () => AuthenticatedHrRoute,
  } as any)

const AuthenticatedHrVacationsIndexRoute =
  AuthenticatedHrVacationsIndexImport.update({
    path: '/',
    getParentRoute: () => AuthenticatedHrVacationsRoute,
  } as any)

const AuthenticatedHrTimekeepingIndexRoute =
  AuthenticatedHrTimekeepingIndexImport.update({
    path: '/',
    getParentRoute: () => AuthenticatedHrTimekeepingRoute,
  } as any)

const AuthenticatedHrFinancesIndexRoute =
  AuthenticatedHrFinancesIndexImport.update({
    path: '/',
    getParentRoute: () => AuthenticatedHrFinancesRoute,
  } as any)

const AuthenticatedHrEmployeesIndexRoute =
  AuthenticatedHrEmployeesIndexImport.update({
    path: '/',
    getParentRoute: () => AuthenticatedHrEmployeesRoute,
  } as any)

const AuthenticatedAccountingCashAccountsIndexRoute =
  AuthenticatedAccountingCashAccountsIndexImport.update({
    path: '/accounting/cashAccounts/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedHrVacationsNewRoute =
  AuthenticatedHrVacationsNewImport.update({
    path: '/new',
    getParentRoute: () => AuthenticatedHrVacationsRoute,
  } as any)

const AuthenticatedHrTimekeepingNewRoute =
  AuthenticatedHrTimekeepingNewImport.update({
    path: '/new',
    getParentRoute: () => AuthenticatedHrTimekeepingRoute,
  } as any)

const AuthenticatedHrEmployeesNewRoute =
  AuthenticatedHrEmployeesNewImport.update({
    path: '/new',
    getParentRoute: () => AuthenticatedHrEmployeesRoute,
  } as any)

const AuthenticatedAccountingCashAccountsNewRoute =
  AuthenticatedAccountingCashAccountsNewImport.update({
    path: '/accounting/cashAccounts/new',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedHrTimekeepingIdIndexRoute =
  AuthenticatedHrTimekeepingIdIndexImport.update({
    path: '/$id/',
    getParentRoute: () => AuthenticatedHrTimekeepingRoute,
  } as any)

const AuthenticatedHrEmployeesIdIndexRoute =
  AuthenticatedHrEmployeesIdIndexImport.update({
    path: '/$id/',
    getParentRoute: () => AuthenticatedHrEmployeesRoute,
  } as any)

const AuthenticatedAccountingCashAccountsIdIndexRoute =
  AuthenticatedAccountingCashAccountsIdIndexImport.update({
    path: '/accounting/cashAccounts/$id/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

const AuthenticatedHrVacationsNewIdRoute =
  AuthenticatedHrVacationsNewIdImport.update({
    path: '/$id',
    getParentRoute: () => AuthenticatedHrVacationsNewRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/hr': {
      id: '/_authenticated/hr'
      path: '/hr'
      fullPath: '/hr'
      preLoaderRoute: typeof AuthenticatedHrImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/hr/debitCreditAnalysis': {
      id: '/_authenticated/hr/debitCreditAnalysis'
      path: '/debitCreditAnalysis'
      fullPath: '/hr/debitCreditAnalysis'
      preLoaderRoute: typeof AuthenticatedHrDebitCreditAnalysisImport
      parentRoute: typeof AuthenticatedHrImport
    }
    '/_authenticated/hr/employees': {
      id: '/_authenticated/hr/employees'
      path: '/employees'
      fullPath: '/hr/employees'
      preLoaderRoute: typeof AuthenticatedHrEmployeesImport
      parentRoute: typeof AuthenticatedHrImport
    }
    '/_authenticated/hr/finances': {
      id: '/_authenticated/hr/finances'
      path: '/finances'
      fullPath: '/hr/finances'
      preLoaderRoute: typeof AuthenticatedHrFinancesImport
      parentRoute: typeof AuthenticatedHrImport
    }
    '/_authenticated/hr/timekeeping': {
      id: '/_authenticated/hr/timekeeping'
      path: '/timekeeping'
      fullPath: '/hr/timekeeping'
      preLoaderRoute: typeof AuthenticatedHrTimekeepingImport
      parentRoute: typeof AuthenticatedHrImport
    }
    '/_authenticated/hr/vacations': {
      id: '/_authenticated/hr/vacations'
      path: '/vacations'
      fullPath: '/hr/vacations'
      preLoaderRoute: typeof AuthenticatedHrVacationsImport
      parentRoute: typeof AuthenticatedHrImport
    }
    '/_authenticated/hr/': {
      id: '/_authenticated/hr/'
      path: '/'
      fullPath: '/hr/'
      preLoaderRoute: typeof AuthenticatedHrIndexImport
      parentRoute: typeof AuthenticatedHrImport
    }
    '/_authenticated/accounting/cashAccounts/new': {
      id: '/_authenticated/accounting/cashAccounts/new'
      path: '/accounting/cashAccounts/new'
      fullPath: '/accounting/cashAccounts/new'
      preLoaderRoute: typeof AuthenticatedAccountingCashAccountsNewImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/hr/employees/new': {
      id: '/_authenticated/hr/employees/new'
      path: '/new'
      fullPath: '/hr/employees/new'
      preLoaderRoute: typeof AuthenticatedHrEmployeesNewImport
      parentRoute: typeof AuthenticatedHrEmployeesImport
    }
    '/_authenticated/hr/timekeeping/new': {
      id: '/_authenticated/hr/timekeeping/new'
      path: '/new'
      fullPath: '/hr/timekeeping/new'
      preLoaderRoute: typeof AuthenticatedHrTimekeepingNewImport
      parentRoute: typeof AuthenticatedHrTimekeepingImport
    }
    '/_authenticated/hr/vacations/new': {
      id: '/_authenticated/hr/vacations/new'
      path: '/new'
      fullPath: '/hr/vacations/new'
      preLoaderRoute: typeof AuthenticatedHrVacationsNewImport
      parentRoute: typeof AuthenticatedHrVacationsImport
    }
    '/_authenticated/accounting/cashAccounts/': {
      id: '/_authenticated/accounting/cashAccounts/'
      path: '/accounting/cashAccounts'
      fullPath: '/accounting/cashAccounts'
      preLoaderRoute: typeof AuthenticatedAccountingCashAccountsIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/hr/employees/': {
      id: '/_authenticated/hr/employees/'
      path: '/'
      fullPath: '/hr/employees/'
      preLoaderRoute: typeof AuthenticatedHrEmployeesIndexImport
      parentRoute: typeof AuthenticatedHrEmployeesImport
    }
    '/_authenticated/hr/finances/': {
      id: '/_authenticated/hr/finances/'
      path: '/'
      fullPath: '/hr/finances/'
      preLoaderRoute: typeof AuthenticatedHrFinancesIndexImport
      parentRoute: typeof AuthenticatedHrFinancesImport
    }
    '/_authenticated/hr/timekeeping/': {
      id: '/_authenticated/hr/timekeeping/'
      path: '/'
      fullPath: '/hr/timekeeping/'
      preLoaderRoute: typeof AuthenticatedHrTimekeepingIndexImport
      parentRoute: typeof AuthenticatedHrTimekeepingImport
    }
    '/_authenticated/hr/vacations/': {
      id: '/_authenticated/hr/vacations/'
      path: '/'
      fullPath: '/hr/vacations/'
      preLoaderRoute: typeof AuthenticatedHrVacationsIndexImport
      parentRoute: typeof AuthenticatedHrVacationsImport
    }
    '/_authenticated/hr/vacations/new/$id': {
      id: '/_authenticated/hr/vacations/new/$id'
      path: '/$id'
      fullPath: '/hr/vacations/new/$id'
      preLoaderRoute: typeof AuthenticatedHrVacationsNewIdImport
      parentRoute: typeof AuthenticatedHrVacationsNewImport
    }
    '/_authenticated/accounting/cashAccounts/$id/': {
      id: '/_authenticated/accounting/cashAccounts/$id/'
      path: '/accounting/cashAccounts/$id'
      fullPath: '/accounting/cashAccounts/$id'
      preLoaderRoute: typeof AuthenticatedAccountingCashAccountsIdIndexImport
      parentRoute: typeof AuthenticatedImport
    }
    '/_authenticated/hr/employees/$id/': {
      id: '/_authenticated/hr/employees/$id/'
      path: '/$id'
      fullPath: '/hr/employees/$id'
      preLoaderRoute: typeof AuthenticatedHrEmployeesIdIndexImport
      parentRoute: typeof AuthenticatedHrEmployeesImport
    }
    '/_authenticated/hr/timekeeping/$id/': {
      id: '/_authenticated/hr/timekeeping/$id/'
      path: '/$id'
      fullPath: '/hr/timekeeping/$id'
      preLoaderRoute: typeof AuthenticatedHrTimekeepingIdIndexImport
      parentRoute: typeof AuthenticatedHrTimekeepingImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren({
  IndexRoute,
  AuthenticatedRoute: AuthenticatedRoute.addChildren({
    AuthenticatedAdminRoute,
    AuthenticatedDashboardRoute,
    AuthenticatedHrRoute: AuthenticatedHrRoute.addChildren({
      AuthenticatedHrDebitCreditAnalysisRoute,
      AuthenticatedHrEmployeesRoute: AuthenticatedHrEmployeesRoute.addChildren({
        AuthenticatedHrEmployeesNewRoute,
        AuthenticatedHrEmployeesIndexRoute,
        AuthenticatedHrEmployeesIdIndexRoute,
      }),
      AuthenticatedHrFinancesRoute: AuthenticatedHrFinancesRoute.addChildren({
        AuthenticatedHrFinancesIndexRoute,
      }),
      AuthenticatedHrTimekeepingRoute:
        AuthenticatedHrTimekeepingRoute.addChildren({
          AuthenticatedHrTimekeepingNewRoute,
          AuthenticatedHrTimekeepingIndexRoute,
          AuthenticatedHrTimekeepingIdIndexRoute,
        }),
      AuthenticatedHrVacationsRoute: AuthenticatedHrVacationsRoute.addChildren({
        AuthenticatedHrVacationsNewRoute:
          AuthenticatedHrVacationsNewRoute.addChildren({
            AuthenticatedHrVacationsNewIdRoute,
          }),
        AuthenticatedHrVacationsIndexRoute,
      }),
      AuthenticatedHrIndexRoute,
    }),
    AuthenticatedAccountingCashAccountsNewRoute,
    AuthenticatedAccountingCashAccountsIndexRoute,
    AuthenticatedAccountingCashAccountsIdIndexRoute,
  }),
  LoginRoute,
})

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_authenticated",
        "/login"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_authenticated": {
      "filePath": "_authenticated.tsx",
      "children": [
        "/_authenticated/admin",
        "/_authenticated/dashboard",
        "/_authenticated/hr",
        "/_authenticated/accounting/cashAccounts/new",
        "/_authenticated/accounting/cashAccounts/",
        "/_authenticated/accounting/cashAccounts/$id/"
      ]
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/_authenticated/admin": {
      "filePath": "_authenticated/admin.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/dashboard": {
      "filePath": "_authenticated/dashboard.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/hr": {
      "filePath": "_authenticated/hr.tsx",
      "parent": "/_authenticated",
      "children": [
        "/_authenticated/hr/debitCreditAnalysis",
        "/_authenticated/hr/employees",
        "/_authenticated/hr/finances",
        "/_authenticated/hr/timekeeping",
        "/_authenticated/hr/vacations",
        "/_authenticated/hr/"
      ]
    },
    "/_authenticated/hr/debitCreditAnalysis": {
      "filePath": "_authenticated/hr/debitCreditAnalysis.tsx",
      "parent": "/_authenticated/hr"
    },
    "/_authenticated/hr/employees": {
      "filePath": "_authenticated/hr/employees.tsx",
      "parent": "/_authenticated/hr",
      "children": [
        "/_authenticated/hr/employees/new",
        "/_authenticated/hr/employees/",
        "/_authenticated/hr/employees/$id/"
      ]
    },
    "/_authenticated/hr/finances": {
      "filePath": "_authenticated/hr/finances.tsx",
      "parent": "/_authenticated/hr",
      "children": [
        "/_authenticated/hr/finances/"
      ]
    },
    "/_authenticated/hr/timekeeping": {
      "filePath": "_authenticated/hr/timekeeping.tsx",
      "parent": "/_authenticated/hr",
      "children": [
        "/_authenticated/hr/timekeeping/new",
        "/_authenticated/hr/timekeeping/",
        "/_authenticated/hr/timekeeping/$id/"
      ]
    },
    "/_authenticated/hr/vacations": {
      "filePath": "_authenticated/hr/vacations.tsx",
      "parent": "/_authenticated/hr",
      "children": [
        "/_authenticated/hr/vacations/new",
        "/_authenticated/hr/vacations/"
      ]
    },
    "/_authenticated/hr/": {
      "filePath": "_authenticated/hr/index.tsx",
      "parent": "/_authenticated/hr"
    },
    "/_authenticated/accounting/cashAccounts/new": {
      "filePath": "_authenticated/accounting/cashAccounts/new.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/hr/employees/new": {
      "filePath": "_authenticated/hr/employees/new.tsx",
      "parent": "/_authenticated/hr/employees"
    },
    "/_authenticated/hr/timekeeping/new": {
      "filePath": "_authenticated/hr/timekeeping/new.tsx",
      "parent": "/_authenticated/hr/timekeeping"
    },
    "/_authenticated/hr/vacations/new": {
      "filePath": "_authenticated/hr/vacations/new.tsx",
      "parent": "/_authenticated/hr/vacations",
      "children": [
        "/_authenticated/hr/vacations/new/$id"
      ]
    },
    "/_authenticated/accounting/cashAccounts/": {
      "filePath": "_authenticated/accounting/cashAccounts/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/hr/employees/": {
      "filePath": "_authenticated/hr/employees/index.tsx",
      "parent": "/_authenticated/hr/employees"
    },
    "/_authenticated/hr/finances/": {
      "filePath": "_authenticated/hr/finances/index.tsx",
      "parent": "/_authenticated/hr/finances"
    },
    "/_authenticated/hr/timekeeping/": {
      "filePath": "_authenticated/hr/timekeeping/index.tsx",
      "parent": "/_authenticated/hr/timekeeping"
    },
    "/_authenticated/hr/vacations/": {
      "filePath": "_authenticated/hr/vacations/index.tsx",
      "parent": "/_authenticated/hr/vacations"
    },
    "/_authenticated/hr/vacations/new/$id": {
      "filePath": "_authenticated/hr/vacations/new/$id.tsx",
      "parent": "/_authenticated/hr/vacations/new"
    },
    "/_authenticated/accounting/cashAccounts/$id/": {
      "filePath": "_authenticated/accounting/cashAccounts/$id/index.tsx",
      "parent": "/_authenticated"
    },
    "/_authenticated/hr/employees/$id/": {
      "filePath": "_authenticated/hr/employees/$id/index.tsx",
      "parent": "/_authenticated/hr/employees"
    },
    "/_authenticated/hr/timekeeping/$id/": {
      "filePath": "_authenticated/hr/timekeeping/$id/index.tsx",
      "parent": "/_authenticated/hr/timekeeping"
    }
  }
}
ROUTE_MANIFEST_END */
